baseURL = 'http://hugo-screencast-duke.s3-website-ap-southeast-1.amazonaws.com'
languageCode = 'en-us'
title = 'The New Hugo Site from Milton Chan in 2024'
theme = "ananke"

[[deployment.targets]]
# An arbitrary name for this target.
name = "awsbucket"
URL = "s3://hugo-screencast-duke/?region=ap-southeast-1" #your bucket here
